version: '3'
services:
  node:
    image: mysteriumnetwork/myst:latest
    command:
      - '--udp.ports=57000:60000'
      - 'service --agreed-terms-and-conditions'
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - myst_net
    ports:
      - '${WG_IFACE_IP}:4449:4449'
      - '57000-60000:57000-60000/udp'
    container_name: myst
    cap_add:
      - NET_ADMIN
    volumes:
      - '/var/lib/mysterium-node:/var/lib/mysterium-node'
      - '/etc/mysterium-node:/etc/mysterium-node'
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
networks:
  myst_net:
    name: myst_net
    driver: bridge
#  nginx_proxy:
#    name: nginx_proxy
#    driver: bridge   